services:
  postgres:
    image: postgres:14
    container_name: todoapps-postgres
    restart: unless-stopped
    env_file:
      - secret/postgres.env
    volumes:
      - todoapps-postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432/tcp"

volumes:
  todoapps-postgres-volume:
    name: todoapps-postgres-volume
    external: true

